---
apiVersion: v1
kind: Service
metadata:
  name: myapp-backend-service
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.labelbackend}}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: '80'
      port: 80
      targetPort: 80
      #nodePort: 30003