---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    app: {{.Values.label}}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: '8080'
      port: 80
      targetPort: 80
      nodePort: 30003