apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress-backend
  namespace: {{.Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: myapp-backend-service
            port:
              number: 80